version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
    threshold: 350
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: false
  identical-code:
    enabled: true
plugins:
  stylelint:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-4
    config:
      extensions:
        - .js
        - .jsx
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: true
      allow_strong_copyleft: true
    issue_override:
      severity: major
exclude_patterns:
  - "node_modules/"
